### ISSUE TITLE
Add visible x,y,z coordinates in render view

### ISSUE THREAD

**Issue by msarvestani** [rordenlab/MRIcroGL#22]
It would be very useful to be able to see live x,y,z coordinates of a mouse click in render view. Thanks!

**Comment by neurolabusc** [comment]
@msarvestani  I have added experimental support for this feature. Do you prefer Windows, Linux or MacOS? I can create a copy for you to try out.

**Comment by msarvestani** [comment]
windows please. Thanks so much!

**Comment by neurolabusc** [comment]
@msarvestani please try the experimental [release v1.2.20210624](https://github.com/rordenlab/MRIcroGL/releases/tag/v1.2.20210624).

**Comment by msarvestani** [comment]
Thanks! Will try and let you know.

**Comment by hanayik** [comment]
@neurolabusc, Just saw this and downloaded to try out. It's so nice! It would be great to have the cut-out only apply to the 3D render and leave the 2D slices intact. Happy to try and make a pull request if you can point me in the right direction.

**Comment by neurolabusc** [comment]
This is a consequence of the fact that the cutout is physically removed from the volume and the gradients are re-computed. This helps the user grasp the orientation of the three planes, emphasizing the crease where the planes join. 

The alternative would be to have the cutout detected by the shader - this is in fact what we do with the clip plane. My rationale is that the clip plane is a single plane, so there is no crease at the intersection.

You can see the difference when the cutout and clip plane are both shown with a glossy shader (see image below). If we apply the cutout in the shader, the cutout in the glossy image would look like what you see in the matte image. 

One could create a rationale for either approach. The appearance is very different, and probably falls to user preference. I do agree that physically removing the cutout from the volume can make the 2D slices look odd. On the other hand, with the new A+C+S+R view, the 2D slices and rendering now correspond to each other when a cutout is not applied.

![glossy](https://user-images.githubusercontent.com/8930807/123827133-5a03e780-d8ce-11eb-92f4-a76ad1b035fe.jpg)
![matte](https://user-images.githubusercontent.com/8930807/123827141-5c664180-d8ce-11eb-8684-279c8b06d7f3.png)

**Comment by msarvestani** [comment]
Thanks Chris, this is exactly what I needed. If it's okay I'll share with collaborators.

**Comment by neurolabusc** [comment]
Sure, the pre-release is available for whoever wants to try it.

**Comment by Jessy-Ding** [comment]
> @msarvestani I have added experimental support for this feature. Do you prefer Windows, Linux or MacOS? I can create a copy for you to try out.

Mac please
