### ISSUE TITLE
Issues building =mricrogl-1.2.20210317

### ISSUE THREAD

**Issue by TheChymera** [rordenlab/MRIcroGL#23]
Hi, I'm trying to build the currently latest version (1.2.20210317) and I get this build error: [build.log](https://github.com/rordenlab/MRIcroGL/files/6697690/build.log).

I think it could be a missing file?

```
Fatal: (2013) Cannot open include file "../Metal-Demos/common/glopts.inc"
```

I am using `=fpc-3.2.2` and `=lazarus-2.0.12`.

**Comment by neurolabusc** [comment]
Please read the [Compiling with the Command Line](https://github.com/rordenlab/MRIcroGL) section of the home page. Specifically, MRIcroGL graphical components like the colorer, fonts, etc are built from the [Metal-Demos](https://github.com/neurolabusc/Metal-Demos) modules. Another complexity is that I want to maintain support for older operating systems which use Python 2.7, so you need to use my special version of Python-for-Lazarus which works with either Python 2.x or Python 3.x (while the latest versions only support 3.x). As noted, for Linux you can choose either GTK2 or QT5 widgets depending on your preference, with an option for GTK3 coming soon.
