### ISSUE TITLE
Depth Picking and Render View Cross Hairs

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/MRIcroGL#24]
This is a [feature request](https://www.nitrc.org/forum/forum.php?thread_id=12643&forum_id=4442) to be able to both display cross hairs on the render view and allow mouse clicks on the render view to change the cross-hair position to the location of a mouse click (see [issue 22](https://github.com/rordenlab/MRIcroGL/issues/22)).

**Comment by neurolabusc** [comment]
The pre-release [v1.2.20210816](https://github.com/rordenlab/MRIcroGL/releases/tag/v1.2.20210816) provides a solution, the method employed is described [here](https://github.com/rordenlab/MRIcroGL/tree/master/DepthPicking)

**Comment by ejstephens** [comment]
Thank you so much - that is exactly the feature that we were using MRIcro for when producing SEEG implantation maps.

**Comment by ejstephens** [comment]
I'm sure it's already being worked on, but when I attempted to open a window with a rendered view only the window crashed out. We would usually have multiple windows of the same scan with different render views (left/right hemisphere, above/below brain,  sagittal cut out at level of hippocampus left/right) and also a 3-plane view - so when I tried to test opening a series of windows I discovered that the current version does not like opening a solitary render view.

**Comment by neurolabusc** [comment]
I can not replicate this issue. Can you please provide the following details.

1. What details are reported about your computer operating system and graphics driver when you choose the 'About' window. I attempted to replicate your problem on an Apple MacBook Air M1 with macOS 11.5.1. The about window reports:

```
1.2.20210816 Cocoa ARM64 LLVM
Author: Chris Rorden
License: BSD 2-Clause
Version 11.5.2 (Build 20G95) MacBookAir10,1
Retina Scale: 2
Apple; OpenGL= 2.1 Metal - 71.7.1; Shader=1.20
2.1 Max 3D texture: 2048
Current texture: 191×256×54 10mb
```

2. Provide the steps to reproduce a crash. Here is what I tried:
 - Launch MRIcroGL and chose `chris_t1` from the `Open standard` menu from the `File` menu.
 - Choose `Display` menu item `Multi-Planar A+C+S+R`. Click on rendering to see interactive graphics.
 - Choose `File` menu item `New Window` to launch a second instance of MRIcroGL.
 - In the new window, choose `chris_t2` from the `Open standard` menu.
 - In the new window, choose the `Render` view from the Display menu.
 - None of these operations generate a crash.

**Comment by neurolabusc** [comment]
Closing this issue. @ejstephens  I was unable to replicate your issues. I tried macOS, Windows and Linux OSes, x86-64 and ARM CPUs, and NVidia, Intel and Apple CPUs. Without any more details, I can not explain your issue.
