### ISSUE TITLE
Is it possible to display color rectangle in colormap combo box?

### ISSUE THREAD

**Issue by hanayik** [rordenlab/MRIcroGL#29]
I _think_ it is [possible in pascal/lazarus](https://wiki.freepascal.org/TComboBox#Owner_drawn_ComboBox), but I don't know if that implementation would work cross platform

Here's a [reference implementation](https://github.com/niivue/niivue-ui/blob/4891e94ec31f7eddde92a370bcf3a51830845ba5/src/components/imageItem.vue#L100) in NiiVue. I'm just creating a css linear gradient style string by looping over the RGBA nodes in the JSON color map. 

Similar to the [NiiVue](https://niivue.github.io/niivue-ui/) and [FSLeyes color drop down widgets](https://open.win.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/quick_start.html)

**Comment by neurolabusc** [comment]
[Preceded_image](https://wiki.freepascal.org/TComboBox#Preceded_image)

**Comment by neurolabusc** [comment]
Here is a minimal working solution. It looks fine, but it does not look or act natively: you can not choose between items using the arrow keys, the currently selected item is not actively highlighted. I really like components to look native, so I am not comfortable with this solution.

[color_table_combo.zip](https://github.com/rordenlab/MRIcroGL/files/7270595/color_table_combo.zip)
![color_combo](https://user-images.githubusercontent.com/8930807/135696854-acc0e2a3-0b50-4c70-972d-724cb3e51558.png)

**Comment by neurolabusc** [comment]
Its a nice idea, but MRIcroGL strives to use native widgets.
