### ISSUE TITLE
Python option to adjust overlay depth

### ISSUE THREAD

**Issue by JeffreyWardman** [rordenlab/MRIcroGL#37]
Is it possible to include the following option:

```
gl.overlaydepth(depthPct)  -> depth percentage of overlay
```

**Comment by neurolabusc** [comment]
I assume you want to change the `overlayDepth` property of the render shader. For shader properties, you can call them by name:
```
import gl
gl.resetdefaults()
gl.loadimage('spm152')
gl.overlayload('spmMotor')
gl.minmax(1, 4, 4)
gl.opacity(1,10)
gl.shaderadjust('overlayDepth', 0.2)
```

**Comment by JeffreyWardman** [comment]
Thanks @neurolabusc! That's exactly what I was after. Cheers!

**Comment by gourdchen** [comment]
That's exactly what I was need, which could be added in the command.md.
