### ISSUE TITLE
option to display a specified number of leading paths in the file navigator pane

### ISSUE THREAD

**Issue by yarikoptic** [rordenlab/MRIcroGL#40]
related to #39 as an option to adjust display of filenames an example of which I use here 
![image](https://user-images.githubusercontent.com/39889/159042475-214b0c60-57c8-45fc-9127-945c554ef5ab.png)

if I have a following filenames structure

```
d1/mn152.nii.gz
d2/mn152.nii.gz
```
opening both of them at the same time would just show two `mni152` entries in the pane, making it impossible to distinguish between the two.  It would be cool if mricrogl helped to make difference obvious. It could be

- manual option on how many leading parent paths to include in the display
- automagic option: if conflict (the same name) is detected, choose sufficient number of leading paths to distinguish

thank you very much in advance

**Comment by neurolabusc** [comment]
Hover the mouse over the filename in the Layers panel to see the full path.

**Comment by yarikoptic** [comment]
seeing full path while hovering is good, but not really a solution since would require mental power to keep mapping from "hovering session" in mind while looking at the paths in the pane.

**Comment by yarikoptic** [comment]
oh, cool, what was done for this @neurolabusc ?

**Comment by neurolabusc** [comment]
Hover solution is implemented. There is always a trade-off between simplicity that eases maintenance as well as consistent behavior for all users and configurability. Moving forward, inherent scriptability of NiiVue can allow you to create custom solutions.
