### ISSUE TITLE
Get MNI coordinates of cluster of intensely bright voxels?

### ISSUE THREAD

**Issue by emilyharriott** [rordenlab/MRIcroGL#42]
Dear MRIcroGL experts,

Summary:
I would like to obtain the MNI coordinates of the center of a cluster of particularly intensely bright voxels. I see that I can get the X,Y,Z coordinates of a cluster of particularly intensely bright voxels but would like to know how to get the MNI coordinates of that cluster. How can I do that?

More information:
I am working on a dataset of ~100 participants with lesions. I segmented and normalized my T1 images to MNI space, registered my native FLAIR images to my standardized T1 images so now the FLAIR images are also standardized, ran these images through the Lesion Segmentation Tool (LST) Lesion Growth Algorithm (LGA) pipeline (Schmidt et al., 2012), and obtained two output images: a version of the FLAIR and a lesion probability map. The lesion probability map is a binary map (each voxel is either white with an intensity of 1 indicating that voxel is a lesion or dark with an intensity of 0 indicating that voxel is not a lesion). Both files are .nii.

I open both of these images (the FLAIR as an image and the lesion probability map as an added overlay) into MRIcroGL. I then select the lesion probability map, click "options", "generate cluster table with options", and then set the threshold intensity to be 1 and the minimum cluster size to be 0. I obtain a table that tells me the volume and X,Y,Z coordinates of each lesion.

How do I get the MNI coordinates of each lesion? 
(also, what exactly are the X,Y,Z coordinates? what space is that in?)

Note:
I read some posts that told me I can enter MNI coordinates and then view that brain location. I don't want to enter MNI coordinates, I want to be given MNI coordinates.

Any assistance you might be able to provide would be greatly appreciated. Additionally, please let me know if my question and/or explanation did not make sense.

Thank you so very much,
Emily Harriott
PhD student, Vanderbilt University

**Comment by neurolabusc** [comment]
First of all, to get meaningful results each individuals images need to be normalized. When we first acquire MRI data, the spatial coordinates refer to the location relative to the isocenter of the magnet, so there will be a lot of variability between people depending on how there head was oriented in the head coil. I would use the [Clinical toolbox](https://www.nitrc.org/projects/clinicaltbx/) to normalize your data.

After normalization, each image will have meaningful Talairach coordinates relative to the MNI template if you used ANT, FSL, etc., or to an average sized brain if you used SPM. Note that [the MNI template is slightly bigger than a typical brain](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6050588/).

Given that you have ~100 individuals, I would automate this with a Matlab, Python or bash script

My first instinct would be to use `fslstats` to report the center of mass for each of your lesion files. The could each be in the [world space coordinates as listed by millimeters from the origin](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates) or in voxel coordinates (row, column, slice).

```
-c           : output centre-of-gravity (cog) in mm coordinates
-C           : output centre-of-gravity (cog) in voxel coordinates
```

So a command might be:

```
fslstats voi.nii -c
-24.891571 40.276462 0.319997 
```
