### ISSUE TITLE
Incompatibility of v1.2.20220720 with Ubuntu 18.04 circumstance

### ISSUE THREAD

**Issue by kytk** [rordenlab/MRIcroGL#43]
Thank you for continuous development of MRIcroGL.

I installed the latest version (v1.2.20220720) on both Ubuntu 18.04 and Ubuntu 20.04.

Though MRIcroGL runs without any problems on Ubuntu 20.04, it fails with Ubuntu 18.04 with the following error;

```
MRIcroGL: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./MRIcroGL)
```

(Both MRIcroGL and MRIcroGL_QT result in the same error.)

The shipped version of libc6 on Ubuntu 18.04 is 2.27 whereas the latest MRIcroGL requires 2.29.

I tried to find a solution, but it seems installing libc>=2.29 might cause several problems system-wide.

Any ideas on how to handle this?

**Comment by neurolabusc** [comment]
@kytk can you tell me if the `MRIcroGL_linux1804.zip` [build](https://github.com/rordenlab/MRIcroGL/releases/tag/v1.2.20220720) works for you. I built this on a headless machine, so I am not sure it works. Beware of glibc prior to [2.29](https://github.com/madler/pigz/issues/68) for heavily multi-threaded usage.

**Comment by kytk** [comment]
@neurolabusc Thank you for your prompt work! MRIcroGL_linux1804.zip works without any problems. Much appreciated.

**Comment by neurolabusc** [comment]
@kytk can you tell me if the menu items in the Scripting/Templates folder work? There were reports that scripting did not work on [Ubuntu 18.04](https://www.nitrc.org/forum/message.php?msg_id=35736) for older MRIcroGL releases.

**Comment by kytk** [comment]
@neurolabusc 

It works. I selected Scripting -> Templates -> {basic, clip, cluster, glass, invert, mip} and everything went smoothly!

I also checked that Scripting -> {New, Save, Open} and found no problems.
