### ISSUE TITLE
Borg_Error for large t (4th dimension) nii.gz files in Windows

### ISSUE THREAD

**Issue by dicemt** [rordenlab/MRIcroGL#44]
I have encountered a display/load error (_Borg_Error_) for large 4D nii.gz files in Windows.
Although I still cannot figure out the exact situations that lead to this error, I have seen the latest MRIcroGL (1.2.20220720) sometimes fails to load large t (4th dimension) nii.gz files and shows _Borg_Error_.

Some (marginal) info:
- The older 1.2.20211006 version has no Borg_Error issues in the same environments.
- If I converted them to uncompressed NIfTI files (*.nii), MRIcroGL displayed them without any issues.
- Large t (4th dim) is not always critical. Not found Borg_Error for HCPpipeline preprocessed nii.gz files (4th dim > 1000)
- (At the moment) I have not seen any issues in small t files (4th dim < 50).
- No issues in 3D volumes (4th dim = 1).
- Modality (function or diffusion) does not matter.

![mricrogl_windows_1_2_20220720](https://user-images.githubusercontent.com/11692488/186293320-d5b7a921-b31f-4016-932b-afef4c4f4f33.png)

To reproduce:
**Dataset 1: Haxby 2001 subj2**
```Python
# haxby2001/subj2/bold.nii.gz
from nilearn import datasets
nilearn.datasets.fetch_haxby()
```

**Dataset 2: ABIDE**
https://s3.amazonaws.com/fcp-indi/data/Projects/ABIDE_Initiative/Outputs/cpac/func_minimal/OHSU_0050147_func_minimal.nii.gz

**My Environment 1:**
MRIcroGL 1.2.20220720 x86-64 FPC
Author: Chris Rorden
License BSD 2-Clause
Windows: 10.0
Intel; OpenGL= 4.6.0 - Build 30.0.101.1122; Shader=4.60 - Build 30.0.101.1122
2.1 Max 3D texture: 2048
Current texture: 64x64x64 1mb

**My Environment 2:**
MRIcroGL 1.2.20220720 x86-64 FPC
Author: Chris Rorden
License BSD 2-Clause
Windows: 10.0
NVIDIA Corporation; OpenGL= 4.6.0 NVIDIA 512.15; Shader=4.60 - NVIDIA
2.1 Max 3D texture: 16384
Current texture: 64x64x64 1mb

**Comment by neurolabusc** [comment]
Can you re-download and test the [latest release](https://github.com/rordenlab/MRIcroGL/releases/tag/v1.2.20220720) it will now report version 1.2.20220720c. If this works for you, I can refresh downloads on NITRC.
