### ISSUE TITLE
Saving T1 + spmT overlay as a single combined nifti file

### ISSUE THREAD

**Issue by TamerGezici** [rordenlab/MRIcroGL#45]
Is it possible to save a T1 (added through open file) and it's spmT overlay (added as an overlay) together as a single nifti file? So that the T1 image is modified to have itself along with the activation maps of the spmT.nii file?

**Comment by neurolabusc** [comment]
To do this, you have to fix the high precision scalar values as a low precision RGB image. Beyond MRIcroGL, NiiVue and FSLeyes, very few NIfTI viewers support RGB NIfTI. Not sure what problem you are trying to solve. You may want to describe your applicaition. Better to preserve the precision of your statistical map.

**Comment by TamerGezici** [comment]
> To do this, you have to fix the high precision scalar values as a low precision RGB image. Beyond MRIcroGL, NiiVue and FSLeyes, very few NIfTI viewers support RGB NIfTI. Not sure what problem you are trying to solve. You may want to describe your applicaition. Better to preserve the precision of your statistical map.

Thanks a lot for your prompt response.

We need activation maps in subject space as a single NifTI or .IMA for a patient who will undergo awake craniotomy. We plan to upload the image to the neuronavigation system which is used in the operating theater. This way will precisely know where to stimulate with the rod and it's relation to the fMRI activation map. The machine either accepts NifTI or .IMA files (it doesnt accept .dcm for example)

**Comment by TamerGezici** [comment]
I don't know if it would accept RBG NIfTI files, I havent tried that. We can try if it loads the visible human. All I know so far is that it can load NIfTI files.

**Comment by TamerGezici** [comment]
Nevertheless, we can test and see if it would load RGB NIfTI files. How can I generate it such way? The statistical precision is not that important for now I guess. We are more interested in the spatial accuracy.
