### ISSUE TITLE
Opening .nii files with MRIcroGL does not work: failed to load function PyLong_FromUnicode

### ISSUE THREAD

**Issue by JohannesWiesner** [rordenlab/MRIcroGL#47]
Hi! I got a fresh installation of MRIcroGL on an Ubuntu 22.04 laptop. I would like to make MRIcroGL the default application for opening `.nii` and `.nii.gz` files. However, when I right click on a `.nii` file and select MRIcroGL as application for opening, I get the following error:

![image](https://user-images.githubusercontent.com/48254290/200867982-7690a838-52fb-47cd-8cb1-dba06dd0f28d.png)

Pressing "OK" does nothing.

**Comment by neurolabusc** [comment]
Unable to replicate with Ubuntu 23.04 (Lunar).
