### ISSUE TITLE
cannot install the linux version on WSL (Ubuntu)

### ISSUE THREAD

**Issue by michaelmcl1960** [rordenlab/MRIcroGL#51]
I am trying to install the linux version of MRIcroGL on WSL. I can doenload the zip file but the download help page says to extract from the ZIP and then run the executable. But what is the executable? I can see a file called MRIcroGL_QT. When I try to execute that I get the error:

Unable to find AFNI_ATLAS_PATH
MRIcroGL/MRIcroGL_QT: symbol lookup error: MRIcroGL/MRIcroGL_QT: undefined symbol: QLCLOpenGLWidget_Create

As if it is expecing that I have setup some environmental variables.

**Comment by michaelmcl1960** [comment]
I would like to run it in Linux also because I use Freesurfer with my linux installation (Ubuntu 22.04)

Is the file ./MRIcroGL_QT the executable the installation help talks about?

Am I correct in typing  ./MRIcroGL_QT to run mricrogl?

How do I try FSLeyes and glxgears?

lsb_release -a 

give me this:

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

How do I try FSLeyes and glxgears?

**Comment by neurolabusc** [comment]
- For FreeSurfer I would use [NiiVue](https://niivue.github.io/niivue/) that supports **both** voxels and mesh formats.
 - Use MRIcroGL_QT if your widgetset is QT5, use MRIcroGL for GTK2. Please see the attached readme.
 - The first hit I found for WSL and FSLeyes is [here](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/Windows) which also suggests trying glxgears. I am not very familiar with Ubuntu, but google suggests `sudo apt install mesa-utils`. The FSL jiscmail may also help.

**Comment by michaelmcl1960** [comment]
Thanks you, have helped a lot. I was able to get fsleyes and glxgears working eventually by following your links.
MRIcroGL_QT is still not working though. I still get the error:
Unable to find AFNI_ATLAS_PATH which goes away if I use :
export AFNI_ATLAS_PATH=/home/michael/MRIcroGL/Resources/atlas
but then I still get the other error:

MRIcroGL/MRIcroGL_QT: symbol lookup error: MRIcroGL/MRIcroGL_QT: undefined symbol: QLCLOpenGLWidget_Create

I think there is some installtion file that I need to run that is not referred to in the documentation

**Comment by michaelmcl1960** [comment]
I got much further!
This got me past that error: 
https://github.com/davidbannon/libqt5pas/releases/tag/v1.2.9

Apparently there is an issue with libqt5pas 

Now I have this error:

_Could not find FB config: will try without multi-sampling
[FORMS.PP] ExceptionOccurred
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $000000000086CCEA_

This sounds like an environmental variable is missing

**Comment by neurolabusc** [comment]
Any luck using the GTK2 version instead of QT5? I have no more insights for supporting this emulated environment.
