### ISSUE TITLE
Decrease line thickness in glass brain?

### ISSUE THREAD

**Issue by Shotgunosine** [rordenlab/MRIcroGL#52]
I'm trying to reproduce a visualization that looks like this:
![Screen Shot 2023-04-06 at 3 19 46 PM](https://user-images.githubusercontent.com/5289368/230494244-c3e03222-a2d3-4570-88a6-b5d100e90592.png)

But with the glass brain option in MRIcroGL, the thickness of the edges gets exagerated, giving it almost a marker-drawn, chunky aesthetic:
![Screen Shot 2023-04-06 at 2 12 17 PM](https://user-images.githubusercontent.com/5289368/230494532-58c163d7-060e-424f-b238-a4d6b705c07b.png)

Is there a way to tweak the glass brain renderer so that it looks more similar to the images I'm trying to reproduce?

**Comment by neurolabusc** [comment]
I would use [Surfice](https://www.nitrc.org/plugins/mwiki/index.php/surfice:MainPage). The Script/Templates/subcortical and Script/Templates/node Python scripts should give you some good ideas.

![surf](https://user-images.githubusercontent.com/8930807/230497675-fa3cd8ec-43fd-4294-b090-f4d1c9c29592.png)
