### ISSUE TITLE
MRICroGL software query

### ISSUE THREAD

**Issue by dbeaver12** [rordenlab/MRIcroGL#54]
Hi..

With ref to a ticket raised on MMU system (71369772), we would like to check on these prior to use in Manchester Metropolitan university one of our departments-
1.	When was software last updated
2.	Is software still on active development
3.	Are the software provider committed to patching the software in event of security incident or known security vulnerabilities.

Please could answer the above-mentioned question about the MRICroGL software.

Thanks, and Regards,
Jesu 

Jesu Mathew 
Software Licensing Administrator

**Comment by neurolabusc** [comment]
1. You can update this yourself by [clicking the MRIcroGL releases](https://github.com/rordenlab/MRIcroGL/releases). 
2. MRIcroGL is considered mature and feature complete. Active development has moved to [NiiVue](https://github.com/niivue/niivue) but minor updates will continue to meet evolving image formats.
3. I suggest [you view the license](https://github.com/rordenlab/MRIcroGL/blob/master/license.txt). I am happy to patch software for vulnerabilities, but I have a heavy teaching,  service, admin and research burdens. Therefore, the most expedient method is for a user to suggest a patch via the pull request mechanism.
