### ISSUE TITLE
Creating random color look up table

### ISSUE THREAD

**Issue by mahirtazwar** [rordenlab/MRIcroGL#56]
How to create a random color look up table so that each label in a segmentation image gets a random color instead of a gradient (similar to the random colormap in fsleyes, or how segmentations are loaded on ITK-SNAP)? In this case, each region of interest with a unique label will have a unique or repeated color (since I have more than 200+ ROIs).

Reference to: _Originally posted by @mahirtazwar in https://github.com/neurolabusc/MRIcroGL10_OLD/issues/35#issuecomment-1626337859_

**Comment by neurolabusc** [comment]
Set the `intent_code` of your [NIfTI header](https://brainder.org/2012/09/23/the-nifti-file-format/) to 1002 to specify [NIFTI_INTENT_LABEL](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h). This will use the same random color scheme as FSLeyes and use nearest neighbor interpolation (to solve the partial volume issue that a voxel that is a mixture of area 17 and area 19 should not be identified as area 18).
