### ISSUE TITLE
Retain thresholds when moving across volumes of 4D NIfTI

### ISSUE THREAD

**Issue by TamerGezici** [rordenlab/MRIcroGL#58]
Hello,

Is it possible to retain or enforce a voxel threshold value while moving through 4D NIfTI image volumes?

For example, below I set the thresholds to 0 to 0.1, however when I move to the next volume it changes, which is fine. But the threshold for the first volume is also reset. How can I retain this threshold across all of the volumes?

![image](https://github.com/rordenlab/MRIcroGL/assets/11014942/4f9fbb8a-3786-41d6-b0b9-e3a07c5eaeb9)

**Comment by neurolabusc** [comment]
This is not possible with MRIcroGL. Many 4D scans have intensity changes across volumes due to T1 effects. There are huge differences in voxel intensity with DWI scans depending on the B-weighting. A modulate like [NiiVue](https://niivue.github.io/niivue/) allows very easy scripting to customize, so that might be one way to develop a viewer specific to your needs.

**Comment by TamerGezici** [comment]
> This is not possible with MRIcroGL. Many 4D scans have intensity changes across volumes due to T1 effects. There are huge differences in voxel intensity with DWI scans depending on the B-weighting. A modulate like [NiiVue](https://niivue.github.io/niivue/) allows very easy scripting to customize, so that might be one way to develop a viewer specific to your needs.

Thanks. Is it not possible using MRIcrogl's custom scripting system?

**Comment by TamerGezici** [comment]
Maybe you misunderstood me and said it was impossible. But after some 20 minutes of reading wiki, I figured out that it can be done like this:

import gl
gl.resetdefaults()

```
gl.shadername('OverlaySurface')
for vol in range(0,18):
	gl.wait(1000)
	gl.volume(1, vol)
	gl.shadername('OverlaySurface')
	gl.minmax(1, 0, 0.1)
	gl.colorname (1,"4hot")
```
