### ISSUE TITLE
[BUG] MRIcroGL shows wrong path when hovering over overlays.

### ISSUE THREAD

**Issue by TamerGezici** [rordenlab/MRIcroGL#59]
When you hover over an overlay at the top-left overlay list, the wrong path/name is presented for the first time you hover over it. You must unhover and hover again and again until it gets the correct one.

Steps to reproduce:

- Load your background image.
- Load 2 overlay images.
- Hover over the first overlay name on the top-left overlay list and see the path at the pop up text.
- Hover over the second overlay name and notice the first path is presented.
- Hover over the second overlay name again and again until it presents the correct path.

![image](https://github.com/rordenlab/MRIcroGL/assets/11014942/af7e282d-6aa1-454e-9e62-1531e077c7e7)

![image](https://github.com/rordenlab/MRIcroGL/assets/11014942/5015b512-5144-4a89-801f-96c09d467179)

**Comment by TamerGezici** [comment]
Noting that it is a minor bug and the possibility of the developers being preoccupied with more important things, I wanted to see where the dialog popped up and it seems like it's here:

https://github.com/rordenlab/MRIcroGL/blob/c2f3b6f18128ea7f802179c61bf116973711af1d/mainunit.pas#L8673C15-L8673C15

However, I am not so sure where the variable **niftiVol.Filename** is set and why it does not immediately update.

**Comment by neurolabusc** [comment]
Will be addressed in future release. While I am glad that MRIcroGL has proven popular and robust, my primary development focus is on [NiiVue](https://github.com/niivue/niivue) so do not expect a rapid resolution.

**Comment by neurolabusc** [comment]
The problem and solution is described [here](https://forum.lazarus.freepascal.org/index.php?topic=52905.0). The OnShowHint event is fired as the event is shown, so setting the hint with this event means that the updated hint will be shown the next time the event is fired. The solution is to set the hint on the OnMouseEnter event, prior to when the hint is displayed.
