### ISSUE TITLE
left/right flip in mosaic mode

### ISSUE THREAD

**Issue by dcoynel** [rordenlab/MRIcroGL#65]
Hi, and thanks for this great app!

I'm trying to display saggital slices in mosaic mode, together with the slice placements being shown on a coronal slice. 

I adapted the example from the scripting page (https://github.com/rordenlab/MRIcroGL/blob/master/PYTHON.md), and it seems as if the slice cut shown is flipped from left to right: instead of showing the cut through the red blob, it shows a cut through the blue one. 

Here is the code to reproduce the issue:

```
import gl
gl.resetdefaults()
#open background image
gl.loadimage('spm152')
#open overlay: show positive regions
gl.overlayload('spmMotor')
gl.minmax(1, 4, 4)
gl.opacity(1,50)
#open overlay: show negative regions
gl.overlayload('spmMotor')
gl.minmax(2, -4, -4)
gl.colorname (2,"3blue")
gl.mosaic("S L+ H -0.1 35 C X -20");
```

![cut](https://github.com/user-attachments/assets/be04b4c7-7903-41bd-aa0a-45f8205b969c)

Did I do something wrong in the mosaic command?

Thanks for your help.

Best,
David

**Comment by neurolabusc** [comment]
@dcoynel well spotted - I tend to use neurological convention, but the cross-slice line for a sagittal slice is LR flipped if in radiological display mode. Do you use Windows, Linux or MacOS - I can send you a beta to test.

**Comment by dcoynel** [comment]
I see, thanks! I use macOS.

**Comment by neurolabusc** [comment]
I have sent a link to a notarized MacOS app at your [institutional email](https://biomedizin.unibas.ch/en/persons/david-coynel/). Please test and close this issue if the new version resolves your problems.
